name: Python Package using Conda

#on: workflow_dispatch
on: 
  schedule:
    - cron: 0 12 * * *

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Check Chrome Driver version
      run: |
        echo CHROMEWEBDRIVER=$CHROMEWEBDRIVER
        $CHROMEWEBDRIVER/chromedriver --version
        export PATH=$CHROMEWEBDRIVER:$PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Grab news from Yahoo
      run: |
        python --version
        python grab.py
    - name: Check repo status 
      run: |
        git status
        cat stamp.txt
        ls -l
    - name: commit back
      run: |
        stamp=$(cat stamp.txt)
        if [[ "$stamp" != "" ]]; then
           git config --global user.email "workflow@noreply.com"
           git config --global user.name "workflow"

           echo stamp=$stamp
           git add $stamp
           git add titles.txt
           git add README.md
           git commit -m "commit back from workflow @$stamp"
           git push
        fi



